### ISSUE TITLE
[BUG] Fonts loaded over internet

### ISSUE THREAD

**Issue by ericaxu** [mrowa44/obsidian-ia-writer#3]
**Describe the Bug**
The theme uses fonts loaded over internet.

**Relevant Screenshots**

**To Reproduce**
Steps to reproduce the behavior, e.g.
Install the theme and restart Obsidian, the fonts are loaded through internet.

**In which mode does the bug occur?**
- [x] Reading/Preview Mode
- [x] Source Mode
- [x] Live Preview

**Which editor are you using?**
- [x] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [x] Public Release (Mobile)
- [x] Insider Release (Desktop)
- [x] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by mrowa44** [comment]
Hey, thanks for opening this. Can you explain why is that bad? The fonts will get cached on the first load. What’s the preferred way of adding fonts to an Obsidian theme beside a locally installed font, which I think would not work on mobile or would be difficult (installing custom fonts on iOS is complicated)? I would just prefer to keep the fonts attached to the theme installation since they’re a big part of the theme.

**Comment by ericaxu** [comment]
> Hey, thanks for opening this. Can you explain why is that bad? The fonts will get cached on the first load. What’s the preferred way of adding fonts to an Obsidian theme beside a locally installed font, which I think would not work on mobile or would be difficult (installing custom fonts on iOS is complicated)? I would just prefer to keep the fonts attached to the theme installation since they’re a big part of the theme.

You can base64 encode the font, which is the standard practice with Obsidian themes. Example: https://github.com/Emrie-Candera/Bubble-Space-Theme/blob/main/obsidian.css

This is bad because Obsidian is a local app, it really shouldn't connect to the internet unless absolutely necessary (e.g. to install a plugin). People even contact us when there are network activities at random times because they get really concerned. In this case, it's not really necessary, and bundling the font reduces the risk of your theme breaking as well, in case the font URL breaks.
