### ISSUE TITLE
[BUG] Tasks doesnt render properly

### ISSUE THREAD

**Issue by danieltomasz** [mrowa44/obsidian-ia-writer#4]
**Describe the Bug**

Tasks 
```
- [ ] Tasks
``` 
arent rendered as tasks, but as a text

Obsidian 1.1.16
theme 3.301
System: MacOS 13.3

**Comment by danieltomasz** [comment]
This is just a decision to render it as in iaWriter?

**Comment by mrowa44** [comment]
Yes, that's on purpose.

**Comment by kerim** [comment]
Is there some way to manually override this? I am using the tasks plugin and it breaks the way that plugin styles tasks. Thanks.
